plugins {
    id 'fabric-loom' version '1.7-SNAPSHOT'
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

repositories {
    mavenCentral()
    maven {
        url 'https://oss.sonatype.org/content/repositories/snapshots'
    }
    maven {
        url 'https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/'
    }
    maven {
        url 'https://maven.nucleoid.xyz/'
        name 'Nucleoid'
    }
    maven {
        url 'https://maven.nucleoid.xyz'
    }
    maven {
        url 'https://maven.impactdev.net/repository/development/'
    }
    maven {
        url = uri("https://maven.pkg.github.com/CobbleStory/CobbleEconomyAPI")
        credentials {
            username = project.findProperty("gpr.user")?.toString()
            password = project.findProperty("gpr.token")?.toString()
        }
    }
}

loom {
    splitEnvironmentSourceSets()

    mods {
        "modid" {
            sourceSet sourceSets.main
            sourceSet sourceSets.client
        }
    }
}

dependencies {
    // To change the versions see the gradle.properties file
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

    // Fabric API. This is technically optional, but you probably want it anyway.
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-lifecycle-events-v1:${project.fabric_version}"

    // Ooey Gooey *moan*
    modImplementation include("eu.pb4:sgui:1.6.1+1.21.1")

    implementation "cloud.commandframework:cloud-core:1.8.4"

    // impactor, pebs and cobble economy api
    implementation "net.impactdev.impactor.api:economy:5.3.0-SNAPSHOT"
    implementation "gg.levely.cobblestory:economy-api:2.0.0"
    modImplementation(files("libs/pebbles-economy-1.0.1-1.21.1.jar"))

    // Cobblemon 1.6
    modImplementation("com.cobblemon:fabric:1.6.1+1.21.1")


    implementation "org.yaml:snakeyaml:2.1"
    modImplementation "me.lucko:fabric-permissions-api:0.3.1"
    compileOnly "net.luckperms:api:5.4"
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
    options.release = 21
}

processResources {
    inputs.property "version", project.version
    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

jar {
    from('LICENSE') // Include the license file

    // Include SnakeYAML from the runtime classpath
    from {
        configurations.runtimeClasspath.filter { it.name.contains('snakeyaml') }.collect { zipTree(it) }
    }
}

