# General Tutor Settings
TutorMoves:
  # The currency which will be used to "purchase" tutor moves.
  # Options: impactor:{currency}, pebbles, beconomy:{currencyType}, ultraeconomy:{currencyType}, ITEMS:{item id}.
  currencyKey: impactor:dollars
  # The cost of teaching moves
  cost: 5000
  # Moves that should not appear in the General Tutor
  Blacklisted-Moves:
    - wish
  # Pokemon that should not be able to use the General Tutor
  Blacklisted-Pokemon:
    - pikachu
# Which types of moves should appear in the Tutor GUI
Move-Options:
  tutorMoves: true
  eggMoves: false
  tmMoves: false
  evolutionMoves: false
  levelUpMoves: false
  formChangeMoves: false
  legacyMoves: false
  specialMoves: false
General-Tutor-GUI:
  # The GUI Title
  title: "<gold>General Tutor"
  # The Size of the Main Tutor GUI (2-6)
  size: 6
  # GUI Elements
  previous-page-item: "minecraft:arrow"
  previous-page-name: "Previous Page"
  previous-page-slot: -1
  next-page-item: "minecraft:arrow"
  next-page-name: "Next Page"
  next-page-slot: -1
  exit-item: "minecraft:barrier"
  exit-name: "Back"
  exit-slot: -1
  alphabetical-sort-item: "minecraft:paper"
  alphabetical-sort-name: "Alphabetical"
  alphabetical-sort-slot: -1
  category-sort-item: "minecraft:name_tag"
  category-sort-name: "Category"
  category-sort-slot: -1
  type-sort-item: "minecraft:gold_ingot"
  type-sort-name: "Type"
  type-sort-slot: -1
  filler-item: "minecraft:light_gray_stained_glass_pane"
Selection-GUI:
    # The GUI Title
    title: "<green>Select a Pokemon"
    # GUI Elements
    filler-item: "minecraft:red_stained_glass_pane"
Confirmation-GUI:
    # The GUI Title
    title: "<yellow>Confirm Move"
    # GUI Elements
    confirm-item: "minecraft:lime_wool"
    confirm-name: "<green>Confirm"
    confirm-slot: -1
    cancel-item: "minecraft:red_wool"
    cancel-name: "<red>Cancel"
    cancel-slot: -1
    display-slot: -1
    filler-item: "minecraft:gray_stained_glass_pane"
# Override the cost of specific moves
# Format - move:cost
Move-Overrides:
  - outrage: 6000
  - dracometeor: 10000

# DON'T TOUCH Config-Version OR THINGS WILL BREAK
Config-Version: 2.3