# DON'T TOUCH Config-Version OR THINGS WILL BREAK
Config-Version: 1.4.0
# General Tutor Settings
TutorMoves:
  # The currency which will be used to "purchase" tutor moves.
  # Options: impactor:{currency}, ITEMS:{item id}.
  currencyKey: impactor:dollars
  # The cost of teaching moves
  cost: 5000
  # Moves that should not appear in the General Tutor
  Blacklisted-Moves:
    - wish
  # Pokemon that should not be able to use the General Tutor
  Blacklisted-Pokemon:
    - pikachu
GUI:
  # The GUI Title
  title: "<red><bold>General Tutor"
  # The Size of the Main Tutor GUI (2-6)
  size: 6
  # GUI Elements
  filler-item: "minecraft:gray_stained_glass_pane"
# Override the cost of specific moves
# Format - move:cost
Move-Overrides:
  - outrage: 6000
  - dracometeor: 10000
